In [1]:
import pandas as pd
data={
    "Tid":["1","2","3","4","5","6","7","8","9","10"],
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital_Status": ["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable_Income": ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}
df=pd.DataFrame(data)
print(df)

  Tid Refund Marital_Status Taxable_Income Cheat
0   1    Yes         Single           125K    No
1   2     No        Married           100K    No
2   3     No         Single            70K    No
3   4    Yes        Married           120K    No
4   5     No       Divorced            95K   Yes
5   6     No        Married            60K    No
6   7    Yes       Divorced           220K    No
7   8     No         Single            85K   Yes
8   9     No        Married            75K    No
9  10     No         Single            90K   Yes

In [2]:
print(df.loc[[0, 4, 7, 8]])

  Tid Refund Marital_Status Taxable_Income Cheat
0   1    Yes         Single           125K    No
4   5     No       Divorced            95K   Yes
7   8     No         Single            85K   Yes
8   9     No        Married            75K    No

In [3]:
print(df.loc[3:7])

  Tid Refund Marital_Status Taxable_Income Cheat
3   4    Yes        Married           120K    No
4   5     No       Divorced            95K   Yes
5   6     No        Married            60K    No
6   7    Yes       Divorced           220K    No
7   8     No         Single            85K   Yes

In [4]:
print(df.iloc[4:9,3:6])

  Taxable_Income Cheat
4            95K   Yes
5            60K    No
6           220K    No
7            85K   Yes
8            75K    No

In [5]:
print(df.iloc[:,1:3])

  Refund Marital_Status
0    Yes         Single
1     No        Married
2     No         Single
3    Yes        Married
4     No       Divorced
5     No        Married
6    Yes       Divorced
7     No         Single
8     No        Married
9     No         Single

In [6]:
df2=pd.read_csv("Iris.csv")

In [7]:
print(df2.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:


df2 = df2.drop("SepalWidthCm", axis=1)

In [9]:
df2.head()

   Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1            1.4           0.2  Iris-setosa
1   2            4.9            1.4           0.2  Iris-setosa
2   3            4.7            1.3           0.2  Iris-setosa
3   4            4.6            1.5           0.2  Iris-setosa
4   5            5.0            1.4           0.2  Iris-setosa

In [10]:
emp={
    "Employee_Id":["101","102","103","104","105"],
    "Name":["Alice", "Bob","Charlie","Diana","Edward"],
    "Department":["HR","IT","IT","Marketing","Sales"],
     "Age": [29,34,41,28,38],
    "Salary": [50000,70000,65000,55000,60000],
    "Years_of_Experience": [4,8,10,3,12],
    "Joining_Date": ["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender": ["Female","Male","Male","Female","Male"],
    "Bonus": [5000,7000,6000,4500,5000],
    "Rating": [4.5,4.0,3.8,4.7,3.5]
}
df3=pd.DataFrame(emp)
df3

,Employee_Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [11]:
df3.shape

(5, 10)

In [12]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_Id          5 non-null      object
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(4), object(5)
memory usage: 528.0+ bytes

In [13]:
df3.describe()

             Age       Salary  Years_of_Experience   Bonus    Rating
count   5.000000      5.00000             5.000000     5.0  5.000000
mean   34.000000  60000.00000             7.400000  5500.0  4.100000
std     5.612486   7905.69415             3.847077  1000.0  0.494975
min    28.000000  50000.00000             3.000000  4500.0  3.500000
25%    29.000000  55000.00000             4.000000  5000.0  3.800000
50%    34.000000  60000.00000             8.000000  5000.0  4.000000
75%    38.000000  65000.00000            10.000000  6000.0  4.500000
max    41.000000  70000.00000            12.000000  7000.0  4.700000

In [14]:
df3.head(5)
df3.tail(3)

,Employee_Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [15]:
float(df3["Salary"].mean())

60000.0

In [17]:
float(df3["Bonus"].sum())

27500.0

In [20]:
float(df3["Age"].min())

28.0

In [23]:
float(df3["Rating"].max())

4.7

In [24]:
df3.sort_values(by="Salary", ascending=False)

,Employee_Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [25]:
def performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df3["Performance"] = df3["Rating"].apply(performance)

df3

,Employee_Id,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [26]:
print(df3.isnull().sum())

Employee_Id            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [27]:
df3 = df3.rename(columns={"Employee_ID": "ID"})

In [28]:
print(df3[df3["Years_of_Experience"] > 5])

  Employee_Id     Name Department  Age  Salary  Years_of_Experience  \
1         102      Bob         IT   34   70000                    8
2         103  Charlie         IT   41   65000                   10
4         105   Edward      Sales   38   60000                   12

  Joining_Date Gender  Bonus  Rating Performance
1   2017-07-19   Male   7000     4.0        Good
2   2013-06-01   Male   6000     3.8     Average
4   2010-11-25   Male   5000     3.5     Average

In [29]:
df3["Tax"] = df3["Salary"] * 0.10

In [30]:
print(df3[df3["Department"] == "IT"])

  Employee_Id     Name Department  Age  Salary  Years_of_Experience  \
1         102      Bob         IT   34   70000                    8
2         103  Charlie         IT   41   65000                   10

  Joining_Date Gender  Bonus  Rating Performance     Tax
1   2017-07-19   Male   7000     4.0        Good  7000.0
2   2013-06-01   Male   6000     3.8     Average  6500.0

In [31]:
df3.to_csv("employees_modified.csv", index=False)

In [32]:
print(df3)

  Employee_Id     Name Department  Age  Salary  Years_of_Experience  \
0         101    Alice         HR   29   50000                    4
1         102      Bob         IT   34   70000                    8
2         103  Charlie         IT   41   65000                   10
3         104    Diana  Marketing   28   55000                    3
4         105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance     Tax
0   2020-03-15  Female   5000     4.5   Excellent  5000.0
1   2017-07-19    Male   7000     4.0        Good  7000.0
2   2013-06-01    Male   6000     3.8     Average  6500.0
3   2021-02-10  Female   4500     4.7   Excellent  5500.0
4   2010-11-25    Male   5000     3.5     Average  6000.0